### PR TITLE
Change to Golang 1.19

### PR DESCRIPTION
**Pull request by superseb**
- Bump to Golang 1.19 
- Remove (unneeded?) manual Golang installation
- Add `golangci-lint` and fix all errors reported
- Change `scripts/validate` to template (from `rancher/go-skel`)
- Bump `rancher/dapper` images used by Drone

As I have no clue how this works, I only validated this by building and being able to run the binary. And some reported issues are "fixed" by ignoring the errors, similar to how it was. There is probably a lot more that can be improved but this gets the basics going and fixed.

### CODE REVIEW

**Comment by l-mb** [comment]
Thanks!

A (quick) review suggests that the code changes are good (I suspect that's removing a lot of unused code?), but we may need a moment to consider how to test this indeed.

Can you attach the linter results before and after? Maybe we can add that to the CI/CD setup in the future.

**Comment by superseb** [comment]
This PR includes installing `golangci-lint` and running it as part of CI (see https://drone-publish.rancher.io/rancher/telemetry/59/1/2)

Output:

```
publish/postgres.go:75:14: Error return value of `tx.Rollback` is not checked (errcheck)
                tx.Rollback()
                           ^                                                                                                                                   
publish/postgres.go:83:14: Error return value of `tx.Rollback` is not checked (errcheck)
                tx.Rollback()
                           ^                                              
publish/postgres.go:96:14: Error return value of `tx.Rollback` is not checked (errcheck)
                tx.Rollback()
                           ^                                              
cmd/client.go:211:9: Error return value of `w.Write` is not checked (errcheck)
        w.Write([]byte("ok"))
               ^                                                
cmd/client.go:216:9: Error return value of `w.Write` is not checked (errcheck)
        w.Write([]byte("ok"))
               ^                                        
cmd/client.go:280:19: Error return value of `ioutil.WriteFile` is not checked (errcheck)
                ioutil.WriteFile(EXISTING_FILE, []byte(want), 0644)
                                ^
cmd/common.go:25:10: Error return value of `w.Write` is not checked (errcheck)
                w.Write(bytes)
                       ^
cmd/server.go:336:20: Error return value of `dbPublisher.Report` is not checked (errcheck)
        dbPublisher.Report(r, ip)
                          ^
main.go:58:9: Error return value of `app.Run` is not checked (errcheck)
        app.Run(os.Args)
               ^
publish/tourl.go:19:2: field `uid` is unused (unused)
        uid              string
        ^
publish/tourl.go:21:2: field `rancherImage` is unused (unused)
        rancherImage     string
        ^
publish/tourl.go:22:2: field `rancherVersion` is unused (unused)
        rancherVersion   string
        ^
collector/project.go:13:7: const `projectLabel` is unused (unused)
const projectLabel = "field.cattle.io/projectId"
      ^
cmd/client.go:34:2: var `caCert` is unused (unused)
        caCert     string
        ^
cmd/client.go:35:2: var `target` is unused (unused)
        target     string
        ^
cmd/server.go:248:6: func `clamp` is unused (unused)
func clamp(i, x, j int) int {
     ^
cmd/server.go:614:6: func `adminUi` is unused (unused)
func adminUi(w http.ResponseWriter, req *http.Request) {
     ^
cmd/client.go:228:10: S1012: should use `time.Since` instead of `time.Now().Sub` (gosimple)
        diff := time.Now().Sub(start).String()
                ^
cmd/client.go:237:9: S1012: should use `time.Since` instead of `time.Now().Sub` (gosimple)
        diff = time.Now().Sub(start).String()
               ^
publish/postgres.go:119:10: S1028: should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)) (gosimple)
                return errors.New(fmt.Sprintf("SELECT 1 == %d?!", one))
                       ^
publish/tourl.go:64:10: S1028: should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)) (gosimple)
                return errors.New(fmt.Sprintf("Server returned %d", res.StatusCode))
                       ^
cmd/server.go:262:36: S1019: should use make([]byte, nCols + 1) instead (gosimple)
                rows = append(rows, make([]byte, nCols+1, nCols+1))
                                                 ^
collector/project.go:171:11: S1002: should omit comparison to bool constant, can be simplified to `!perClusterCatalogMap[perClusterKey]` (gosimple)
                                                        if perClusterCatalogMap[perClusterKey] != true {
                                                           ^
cmd/client.go:162:5: S1000: should use for range instead of for { select {} } (gosimple)
                                for {
                                ^
                                ^
collector/cluster.go:207:15: ineffectual assignment to err (ineffassign)
                projectCli, err := GetProjectClient(c, systemProjectID)
                            ^
collector/project.go:208:3: ineffectual assignment to templateVersionNamespace (ineffassign)
                templateVersionNamespace = "cattle-global-data"
                ^
collector/setting.go:12:4: ineffectual assignment to setting (ineffassign)
                        setting, err = client.Setting.Create(&rancher.Setting{
                        ^
cmd/client.go:128:3: ineffectual assignment to clientVersion (ineffassign)
                clientVersion = "unknown"
                ^
cmd/server.go:568:7: ineffectual assignment to err (ineffassign)
        opt, err := getOptions(req, RequiredOptions{"Uid"})
             ^
```

**Review by p-se — APPROVED** [review]
lgtm

**Comment by 0xavi0** [comment]
Although it's been already merged I've tested this anyway.

jsons obtained from Rancher Manager are equal before and after the changes: (except obviously for the date)
```bash
diff json_after_changes.json json_before_changes.json 
198c198
<   "ts": "2023-02-23T11:48:12Z"
---
>   "ts": "2023-02-23T11:41:37Z"
```

I've also tested the server side and it sends results correctly to postgres. (red line is the mark to separate before and after the changes)

Screenshot 2023-02-23 at 12 56 03

**Pull request merged**
