### PR TITLE
use cluster link for namespace

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/14881

**Comment by cjellick** [comment]
please improve commit message

the goal should be that a year from now you or i can read the commit message and know what the problem was and why/how we were fixing it

**Comment by StrongMonkey** [comment]
@cjellick commit is updated.

**Comment by StrongMonkey** [comment]
@cjellick updated :).

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
